### ISSUE TITLE
How about an even dumber short-hand syntax?

### ISSUE THREAD

**Issue by ShaneKilkelly** [treenotation/dumbdown#4]
For example:

```
.t This is Dumbdown. The keyword for title is `.t`.
.ts Dumbdown compiles to html.
.p Dumbdown is an alternative to Markdown.

.p Blank lines get turned into <br>

.li https://treenotation.org/ It is built on Tree Notation

.c
 alert(`The keyword for code blocks is "code"`)

.ls
 .i Dumbdown supports lists
 .i For now the keyword for an item is `.i`
 .i This is a very early version
 .i Dumbdown is released to the public domain
 .i If you want to make it better, please do!
```

**Comment by breck7** [comment]
Interesting!

I prototyped your idea [here](https://jtree.treenotation.org/designer/#grammar%0A%20tooling%20onsave%20jtree%20build%20produceLang%20dumbdown%0A%20anyCell%0A%20blankCell%0A%20dashCell%0A%20%20highlightScope%20constant.language%0A%20codeCell%0A%20%20highlightScope%20comment%0A%20keywordCell%0A%20%20highlightScope%20keyword%0A%20textCell%0A%20%20highlightScope%20string%0A%20urlCell%0A%20%20highlightScope%20constant.language%0A%20errorNode%0A%20%20baseNodeType%20errorNode%0A%20dumbdownNode%0A%20%20extensions%20dd%20dumbdown%0A%20%20description%20A%20prefix%20Tree%20Language%20that%20compiles%20to%20HTML.%20An%20alternative%20to%20Markdown.%0A%20%20root%0A%20%20inScope%20abstractTopLevelNode%20blankLineNode%0A%20%20catchAllNodeType%20errorNode%0A%20%20compilesTo%20html%0A%20%20example%0A%20%20%20title%20Hello%20world%0A%20%20%20subtitle%20This%20is%20dumbdown%0A%20%20%20%0A%20%20%20paragraph%20It%20compiles%20to%20HTML.%20Blank%20lines%20get%20turned%20into%20brs.%0A%20%20%20link%20https%3A%2F%2Ftreenotation.org%20dumbdown%20is%20a%20Tree%20Language.%0A%20%20%20list%0A%20%20%20%20-%20It%20has%20lists%0A%20%20%20%20-%20Too!%0A%20%20%20code%0A%20%20%20%20%2F%2F%20You%20can%20add%20code%20as%20well.%0A%20%20%20%20print(%22Hello%20world%22)%0A%20abstractTopLevelNode%0A%20%20abstract%0A%20%20cells%20keywordCell%0A%20titleNode%0A%20%20catchAllCellType%20textCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Ch1%3E%7BtextCell%7D%3C%2Fh1%3E%0A%20%20crux%20.t%0A%20linkNode%0A%20%20cells%20keywordCell%20urlCell%0A%20%20catchAllCellType%20textCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Ca%20href%3D%22%7BurlCell%7D%22%3E%7BtextCell%7D%3C%2Fa%3E%0A%20%20crux%20.li%0A%20paragraphNode%0A%20%20inScope%20linkNode%0A%20%20catchAllCellType%20textCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cp%3E%7BtextCell%7D%3C%2Fp%3E%0A%20%20crux%20.p%0A%20subtitleNode%0A%20%20catchAllCellType%20textCell%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Ch2%3E%7BtextCell%7D%3C%2Fh2%3E%0A%20%20crux%20.ts%0A%20codeNode%0A%20%20description%20A%20code%20block.%0A%20%20catchAllNodeType%20lineOfCodeNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20todo%20Fix%20spacing%0A%20%20compiler%0A%20%20%20openChildren%20%3Ccode%3E%0A%20%20%20closeChildren%20%3C%2Fcode%3E%0A%20%20%20stringTemplate%20%0A%20%20crux%20.c%0A%20listNode%0A%20%20inScope%20dashNode%0A%20%20extends%20abstractTopLevelNode%0A%20%20compiler%0A%20%20%20stringTemplate%20%0A%20%20%20openChildren%20%3Cul%3E%0A%20%20%20closeChildren%20%3C%2Ful%3E%0A%20%20crux%20.ls%0A%20blankLineNode%0A%20%20description%20Blank%20lines%20compile%20to%20a%20br%20in%20the%20HTML.%0A%20%20cells%20blankCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cbr%3E%0A%20%20pattern%20%5E%24%0A%20%20tags%20doNotSynthesize%0A%20lineOfCodeNode%0A%20%20catchAllCellType%20codeCell%0A%20%20cells%20codeCell%0A%20dashNode%0A%20%20crux%20.i%0A%20%20catchAllCellType%20textCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%3Cli%3E%7BtextCell%7D%3C%2Fli%3E%0A%20%20cells%20dashCell%0Asample%0A%20.t%20This%20is%20MiniDumbdown.%20The%20keyword%20for%20title%20is%20%60.t%60.%0A%20.ts%20MiniDumbdown%20compiles%20to%20Dumbdown.%0A%20.p%20MiniDumbdown%20is%20an%20alternative%20to%20Dumbdown%20with%20abbreviations%20instead%20of%20words.%0A%20%0A%20.p%20Blank%20lines%20get%20turned%20into%20%3Cbr%3E%0A%20%0A%20.li%20https%3A%2F%2Ftreenotation.org%2F%20It%20is%20built%20on%20Tree%20Notation%0A%20%0A%20.c%0A%20%20alert(%60The%20keyword%20for%20code%20blocks%20is%20%22.c%22%60)%0A%20%0A%20.ls%0A%20%20.i%20Dumbdown%20supports%20lists%0A%20%20.i%20For%20now%20the%20keyword%20for%20an%20item%20is%20%60.i%60%0A%20%20.i%20This%20is%20a%20very%20early%20version%0A%20%20.i%20Dumbdown%20is%20released%20to%20the%20public%20domain%0A%20%20.i%20If%20you%20want%20to%20make%20it%20better%2C%20please%20do!).

I think this would be a good
candidate for "DumbdownLite" or "Mini-Dumbdown".

It would be easy to compile this to verbose Dumbdown,
and then people could choose to write in one or the other
(but parsers would only have to worry about parsing
verbose Dumbdown).

I agree that something like this could be very handy
especially when using plain text editors.

**Comment by lucianmarin** [comment]
Why not [Haml](https://haml.info)?

**Comment by breck7** [comment]
@lucianmarin there's actually a
strong connection between Tree Notation
and HAML (https://faq.treenotation.org/#how-was-tree-notation-discovered)
